import Link from "next/link";
import "./global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <header className="p-10 text-center bg-slate-800">
          <h1 className="text-white">Header</h1>
        </header>
        <main className="w-full h-full m-auto text-center">
          <div className="m-auto h-full w-full">
            <>{children}</>
            <Link href="/">Home</Link>
          </div>
        </main>
        <footer className="p-3 text-center bg-slate-800 fixed text-white left-0 bottom-0 w-full">
          Footer
        </footer>
      </body>
    </html>
  );
}
